// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 5.3
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_basic(c,a,b){this.go=function(d){b.find("ul").css("transform","translate3d(0,0,0)").stop(true).animate({left:(d?-d+"00%":(/Safari/.test(navigator.userAgent)?"0%":0))},c.duration,"easeInOutExpo");return d}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 5.3
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"basic",prev:"",next:"",duration:20*100,delay:20*100,width:800,height:600,autoPlay:false,playPause:false,stopOnHover:false,loop:false,bullets:0,caption:false,captionEffect:"slide",controls:true,onBeforeStep:0,images:[{src:"./dsc_0989.jpg",title:"DSC_0989"},{src:"./dsc_10101.jpg",title:"DSC_1010-1"},{src:"./dsc_1011.jpg",title:"DSC_1011"},{src:"./dsc_1248.jpg",title:"DSC_1248"},{src:"./dsc_1289.jpg",title:"DSC_1289"},{src:"./dsc_1299.jpg",title:"DSC_1299"},{src:"./dsc_1550.jpg",title:"DSC_1550"},{src:"./dsc_1948.jpg",title:"DSC_1948"},{src:"./hm1_2759.jpg",title:"HM1_2759"},{src:"./hm1_2763.jpg",title:"HM1_2763"},{src:"./hm1_2772.jpg",title:"HM1_2772"},{src:"./hm1_2895.jpg",title:"HM1_2895"},{src:"./hm1_2961.jpg",title:"HM1_2961"},{src:"./hm1_2970.jpg",title:"HM1_2970"},{src:"./hm1_2984.jpg",title:"HM1_2984"},{src:"./hm1_2985.jpg",title:"HM1_2985"},{src:"./hm2_1482.jpg",title:"HM2_1482"},{src:"./hm2_1484.jpg",title:"HM2_1484"},{src:"./hm2_1485.jpg",title:"HM2_1485"},{src:"./hm2_1487.jpg",title:"HM2_1487"},{src:"./hm2_1489.jpg",title:"HM2_1489"},{src:"./hm2_1544.jpg",title:"HM2_1544"},{src:"./hm2_1833.jpg",title:"HM2_1833"}]});