// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 5.3
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_basic(c,a,b){this.go=function(d){b.find("ul").css("transform","translate3d(0,0,0)").stop(true).animate({left:(d?-d+"00%":(/Safari/.test(navigator.userAgent)?"0%":0))},c.duration,"easeInOutExpo");return d}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 5.3
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container2").wowSlider({effect:"basic",prev:"",next:"",duration:9*100,delay:20*100,width:800,height:600,autoPlay:false,playPause:false,stopOnHover:false,loop:false,bullets:0,caption:false,captionEffect:"slide",controls:true,onBeforeStep:0,images:[{src:"./dsa_6597.jpg",title:"DSA_6597"},{src:"./dsa_6687.jpg",title:"DSA_6687"},{src:"./dsa_7724.jpg",title:"DSA_7724"},{src:"./dsa_62551.jpg",title:"DSA_62551"},{src:"./dsc_3256.jpg",title:"DSC_3256"},{src:"./dsc_6034.jpg",title:"DSC_6034"},{src:"./dsc_6127.jpg",title:"DSC_6127"},{src:"./dsc_6132.jpg",title:"DSC_6132"}]});